#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure home page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure /redirect_me to redirect to the direction bellow.
direction="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i "s@^\troot /var/www/html;@&\n\tlocation /redirect_me {\n\t\t return 301 '${direction}';\n\t}@" /etc/nginx/sites-available/default

sudo service nginx start
