#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page\\n" | sudo tee /var/www/html/404.html
REDIRECTION="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i "s@^\troot /var/www/html;@&\n\n\tlocation /redirect_me {\n\t\treturn 301 ${REDIRECTION};\n\t}@" /etc/nginx/sites-available/default
sudo sed -i "s@^\troot /var/www/html;@&\n\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t\treturn 404;\n\t}@" /etc/nginx/sites-available/default
sudo service nginx start
