#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee '/var/www/html/index.html'
echo "Ceci n'est pas une page" | sudo tee '/var/www/html/error_404.html'
REDIRECTION="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i "s@^\troot /var/www/html;@&\n\n\tlocation /redirect_me {\n\t\treturn 301 ${REDIRECTION};\n\t}\n@" /etc/nginx/sites-available/default
sudo sed -i "s@^\troot /var/www/html;@&\n\n\terror_page 404 /error_404.html;\n\n\tlocation = /error_404.html {\n\t\tinternal;\n\t}\n@" /etc/nginx/sites-available/default

sudo service nginx start
