#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header {X-Served-By: hostname of the server Nginx}

file="/etc/nginx/nginx.conf"
script="\%^http {%a\ \t# custom header\n\tadd_header X-Served-By \${hostname};\n"
sudo sed -i "${script}" "${file}"
sudo service nginx restart
