#!/usr/bin/env bash
# Configures a brand new Ubuntu machine
sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" > index.html
echo "Ceci n'est pas une page" > 404.html
sudo mv index.html 404.html /var/www/html/

REDIRECTION="https://www.google.com/"
echo -e '\n\t# Custom header' > file.txt
echo -e '\tadd_header X-Served-By '\"$(hostname)\"';' >> file.txt
echo -e '\n\t# Redirection' >> file.txt
echo -e '\tlocation /redirect_me {\n\t\treturn 301 '${REDIRECTION}';\n\t}' >> file.txt
echo -e '\n\t# Custom error page' >> file.txt
echo -e '\terror_page 404 /404.html;' >> file.txt
echo -e '\tlocation = /404.html {\n\t\tinternal;\n\t}' >> file.txt

FILE="/etc/nginx/sites-available/default"
PATTERN="^\troot /var/www/html;"

sudo sed -i "\%${PATTERN}%rfile.txt" "${FILE}"
rm file.txt

sudo service nginx restart
