#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
#	In between each iteration of the loop, program pause for 2 seconds
#	displays I am invincible!!! when receiving a SIGTERM signal
while :
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" TERM
	
done
