#!/usr/bin/env bash
# Bash script that loops from 0 to 9 
# 	if 4th iteration displays bad luck,
#	if 8th displays good luck
#	else displays Best School
_i="0"
while [ $_i -lt 10 ]
do
	if [ $_i -eq 3 ]; then echo bad luck # 4th iteartion in the loop, since  _i starts from 0
	elif [ $_i -eq 7 ]; then echo good luck # 8th iteartion in the loop, since  _i starts from 0
	else
		echo Best School
	fi
	_i=$((_i+1))
done
