#!/usr/bin/env bash
# Bash script that loops from 0 to 9 
# 	if 4th iteration displays bad luck,
#	if 8th displays good luck
#	else displays Best School
_i="0"
while [ $_i -lt 10 ]
do
	if [ $_i -eq 4 ]; then echo bad luck
	elif [ $_i -eq 8 ]; then echo good luck
	else
		echo Best School
	fi
	_i=$((_i+1))
done
