#!/usr/bin/env bash
# Bash script that loops from 0 to 9 
# 	if 4th iteration displays bad luck,
#	if 8th displays good luck
#	else displays Best School
_m="0"
_h="0"
while [ $_h -lt 13 ]
do
	if (( _m % 60 == 0 ))
	then
		echo Hour: $_h
		_h=$((_h+1))
		_m="1"
	else
		echo $_m
		_m=$((_m+1))
	fi
done
