#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

_m="0"
_h="0"
while [ $_h -le 12 ]
do
	if (( _m == 0 )); then
		echo Hour: $_h
		_m="1"
	elif (( _m == 60 )); then
		_h=$((_h+1))
		_m="0"
	else
		echo $_m
		_m=$((_m+1))
	fi
done
