#!/usr/bin/env bash
# Bash script that displays the content of the current directory
# in a list format, where only the part of the name after the first dash is displayed

for f in *
do
	
	cut -d "-" -f2 <<< "$f"
done
