#!/usr/bin/env bash
# Bash script that displays Best School 10 times using For loop
# shellcheck disable=SC2034

if [ -e ./school ]
	then
		echo "school file exists"
		if [ ! -s ./school ]; then echo "school file is empty"
		else echo "school file is not empty"
		fi

		if [ -f ./school ]; then echo "school is a regular file"; fi
else echo "school file does not exist"
fi

