#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
#	Requirements:
#	- localhost resolves to 127.0.0.2
#	- facebook.com resolves to 8.8.8.8

ORIGIN="/etc/hosts"
COPY="new_host"
cp "$ORIGIN" "$COPY"
sed -i.bak "s/127.*localhost/127.0.0.2       localhost/" "$COPY"
echo "8.8.8.8       facebook.com" >> "$COPY"
cp "$COPY" "$ORIGIN"
