#!/usr/bin/env bash
# Bash script that configures Nginx web server to run with the user nginx and to listen on all active IPs on port 8080
sed -i 's/[0-9]\+ default/8080 default/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
