#!/usr/bin/env bash
# Send a HUP signal to Gunicorn processes to reload it in a graceful way
GUNICORN_PIDs=$(pgrep "gunicorn")
if [ -n "$GUNICORN_PIDs" ]; then
	for PID in $GUNICORN_PIDs; do
		kill -HUP "$PID"
	done
fi
