#!/usr/bin/env bash
# Bash script that uses ssh to connect to a server using server ip address, the private key ~/.ssh/school with the user ubuntu
server="54.236.48.13".
ssh -i ~/.ssh/school ubuntu@$server
